@baseUrl = http://localhost:3000/api

### GET /api - 404
GET {{baseUrl}}

### GET /api/does-not-exist - 404
GET {{baseUrl}}/does-not-exist

### GET ALL entries
GET {{baseUrl}}/entries

###
POST {{baseUrl}}/entries
Content-Type: application/json

{
  "text": "Some text",
  "author": "Jane"
}

### TOGGLE MARK-AS-DONE
PATCH {{baseUrl}}/entries/mark-as-done
Content-Type: application/json

{
  "_id": "6239d3bb7b83e64ce6a997ff"
}

### DELETE

DELETE {{baseUrl}}/entries
Content-Type: application/json

{
  "_id": "6238504239de179b59e7deb2"
}